- AnaliseProjeto/AgendeMe.mdj
Por favor, revisem e vejam os relacionamentos das entidades em cada diagrama.
> Diagramas adicionados Resolve #6

- AnaliseProjeto/AgendeMe.mdj
Boa tarde. 
Os diagramas de classe referentes aos casos de uso 06 (Autenticar Cidadão) e 10 (Atender Cidadão) foram adicionados ao arquivo "AgendeMe" do StarUML. 
Por favor, solicito a revisão das inclusões e alterações realizadas no arquivo. Desde já, agradeço.
> Adição dos diagramas de classe dos casos de uso 06 (Autenticar Cidadão) e 10 (Atender Cidadão)

- AnaliseProjeto/AgendeMe.mdj
Peço a revisão dos revisores designados sobre os 3 diagramas de classe dos casos de uso 7, 8 e 9.
> Criado diagramas de classe dos casos de uso 7,8 e 9. resolved #8

- AnaliseProjeto/AgendeMe.mdj
Boa tarde. 
Realizei a adição e alteração de determinados atributos nas entidades do diagrama DER. Deste modo, solicito a revisão das modificações realizadas.
Desde já, agradeço. Bom trabalho a todos!
> Adição e alteração dos atributos nas entidades do diagrama DER referente a issue #18. 

- AnaliseProjeto/AgendeMe.mdj
Bom dia. 
De acordo com o que foi requisitado nos comentários da issue #24, a entidade "Agendamento" foi atualizada.
Solicito a revisão das alterações realizadas.
Desde já, agradeço.
> Atualização da entidade "Agendamento"

- AnaliseProjeto/AgendeMe.mdj
Foi adicionado o novo caso de uso "Manter Profissional" no diagrama de caso de uso no UML.
> Adicionado novo caso de uso no Diagrama de Caso de Uso

- AnaliseProjeto/AgendeMe.mdj
Os atributos da entidade "Agenda" foram atualizados de acordo com a descrição da issue #31.
> Atualização dos atributos da entidade "Agenda" no StarUML.

- AnaliseProjeto/AgendeMe.mdj
Boa tarde. 
Assim como solicitado na issue #34, o caso de uso "Manter Agendamento", o diagrama de classe "UC-Manter Agendamento" e a boundary "TelaManterAgendamento" foram alterados. Houve a substituição de "Manter Agendamento" por "Agendar Serviço".
Deste modo, solicito a revisão as modificações realizadas. Desde já, agradeço.
> Atualização do caso de uso, do diagrama de classe e da boundary relacionados a "Manter Agendamento"

- AnaliseProjeto/AgendeMe.mdj
Boa noite!
O relacionamento entre a entidade "Agendamentos" e a entidade "Agendamentos" foi adicionada. Esse relacionamento diz respeito há questão do retorno referente a um determinado agendamento. 
Desde modo, solicito a revisão das modificações realizadas. Desde já, agradeço.
> Adição do relacionamento entre a entidade "Agendamentos" e a entidade "Agendamentos"

- AnaliseProjeto/AgendeMe.mdj
Nome de Manter Agenda atualizado para Manter Agenda do Servico Resolve #23
> Nome de Manter Agenda atualizado para Manter Agenda... Resolve #23

- AnaliseProjeto/AgendeMe.mdj
Boa noite.
O relacionamento entre a entidade "Agendamentos" e a entidade "ServicoPublico" foi adicionado. O mesmo, pode ser visualizado no diagrama de classe "UC-Agendar Servico".
Por favor, realizem a revisão do que foi adicionado com a devida atenção. Desde já, agradeço.
> Adição do relacionamento entre as entidades "Agendamentos" e "ServicoPublico"

- AnaliseProjeto/AgendeMe.mdj
Boa noite!
O relacionamento entre a entidade "OrgaoPublico" e a entidade "Prefeitura" foi adicionado. Onde, um órgão público está associado a uma prefeitura e, uma prefeitura pode ter vários órgãos públicos.
Este relacionamento pode ser visualizado no diagrama de classe "UC-Manter Orgao Publico".
Solicito a revisão das modificações realizadas. Desde já, agradeço.
> Adição do relacionamento entre as entidades "OrgaoPublico" e "Prefeitura" 

- AnaliseProjeto/AgendeMe.mdj
Boa noite!
O relacionamento entre a entidade "Agendamento" e a entidade "Profissional" foi adicionada. Neste relacionamento, um agendamento está associado a um profissional e, um profissional pode estar associado a vários agendamentos. 
Tal relacionamento pode ser visualizado no diagrama de classe "UC-Agendar Servico".
Solicito a revisão das modificações realizadas. Desde já, agradeço.
> Adição do relacionamento entre as entidades "Agendamentos" e "Profissional"

- AnaliseProjeto/AgendeMe.mdj
Revisar diagrama de classe do caso de uso Manter Profissional dentro de Analysis Model no Star UML.
> Adicionado diagrama de classe de Manter Profissional. resolved #52

- AnaliseProjeto/AgendeMe.mdj
Removido todos os métodos das entidades
> Metodos removidos #54

- AnaliseProjeto/AgendeMe.mdj
Boa tarde.
Os artefatos "ControladorRetorno" e "PersistenciaRetorno" foram removidos. Além disso, foram adicionados os artefatos "ControladorAgendamento" e "PersistenciaAgendamento" foram adicionados no diagrama de classe "UC-Agendar Retorno".
Solicito a revisão. Desde já, agradeço.
> Remoção dos artefatos "ControladorRetorno" e "PersistenciaRetorno"

- AnaliseProjeto/AgendeMe.mdj
Boa tarde.
O relacionamento entre as entidades "AgendaDoServico" e "Agendamentos" foi removido do DER. 
Por favor, verificar as alterações realizadas.
> Remoção do relacionamento entre as entidades "AgendaDoServico" e "Agendamentos"

- AnaliseProjeto/AgendeMe.mdj
Dentro do arquivo verificar se o diagrama de classe do caso de uso Manter Profissional foi modificada corretamente, sendo que objetivo era adicionar uma classe boundary para ela.
> Modificações foram feitas no arquivo "AgendeMe.mdj". Done #63

- AnaliseProjeto/AgendeMe.mdj
criada entidade "Especialidade" para relacionar com entidade Profissional.
> criada entidade Especialidade no UML. 

- Codigo/AgendeMe.sln
- Codigo/AgendeMeWeb/appsettings.json
- Codigo/Core/Agendadoservico.cs
- Codigo/Core/Agendamento.cs
- Codigo/Core/AgendeMeContext.cs
- Codigo/Core/Areadeservico.cs
- Codigo/Core/Atendenteorgaopublico.cs
- Codigo/Core/Cargo.cs
- Codigo/Core/Cidadao.cs
- Codigo/Core/Core.csproj
- Codigo/Core/Orgaopublico.cs
- Codigo/Core/Prefeitura.cs
- Codigo/Core/Profissionalcargo.cs
- Codigo/Core/Profissionalprefeitura.cs
- Codigo/Core/Service/IAgendaDoServicoService.cs
- Codigo/Core/Service/IAgendamentoService.cs
- Codigo/Core/Service/IAreaDeServicoService.cs
- Codigo/Core/Service/ICargoService.cs
- Codigo/Core/Service/ICidadaoService.cs
- Codigo/Core/Service/IOrgaoPublicoService.cs
- Codigo/Core/Service/IPrefeituraService.cs
- Codigo/Core/Service/IServicoPublicoService.cs
- Codigo/Core/Servicopublico.cs
Revisar se o tutorial foi seguido da forma correta
> Adicionado projeto Core e primeiros arquivos Core

- Codigo/AgendeMeWeb/AgendeMeWeb.csproj
Verificar se o pacote "AutoMapper.Extension.Microsoft.DependencyInjection" está listado no conjunto de pacotes(packages) da dependência do projeto AgendeMeWeb.
> Adicionado AutoMapper ao conjunto de depedencias do AgendeMeWeb

- Codigo/AgendeMeWeb/Program.cs
Boa noite.
A conexão com os services e o banco de dados foi adicionada na classe "Program" presente no projeto "AgendeMeWeb".
Por favor, realizar a revisão das modificações realizadas. Desde já, agradeço.
> Adição da conexão com os services e o banco de dados

- Codigo/AgendeMe.sln
- Codigo/Util/CPFAttribute.cs
- Codigo/Util/CepAttribute.cs
- Codigo/Util/Methods.cs
- Codigo/Util/TelefoneCelularAttribute.cs
- Codigo/Util/TelefoneFixoAttribute.cs
- Codigo/Util/Util.csproj
O projeto Util foi adicionado a solução.
Nele, estão presentes as classes e métodos referentes a determinadas validações.
Por favor, realizar a revisão das modificações realizadas.
> Adição do projeto Util e suas classes com métodos de validação

- Codigo/AgendeMeWeb/Controllers/AreaDeServicoController.cs
- Codigo/AgendeMeWeb/Mappers/AreaDeServicoProfile.cs
- Codigo/AgendeMeWeb/Models/AreaDeServicoViewModel.cs
- Codigo/AgendeMeWeb/Program.cs
- Codigo/AgendeMeWeb/Views/AreaDeServico/Create.cshtml
- Codigo/AgendeMeWeb/Views/AreaDeServico/Delete.cshtml
- Codigo/AgendeMeWeb/Views/AreaDeServico/Details.cshtml
- Codigo/AgendeMeWeb/Views/AreaDeServico/Edit.cshtml
- Codigo/AgendeMeWeb/Views/AreaDeServico/Index.cshtml
- Codigo/Core/Service/IAreaDeServicoService.cs
- Codigo/Service/AreaDeServicoService.cs
Por favor, testar criar, editar e deletar. Além de verificar se o código está seguindo as boas práticas.
Caso seja necessário, execute o script para cadastrar uma prefeitura no banco, pois a área de serviço necessita referenciar uma prefeitura:
```
INSERT INTO PREFEITURA(id,nome,cnpj,estado,cidade,bairro,cep,rua,numero,icone)
value(null,'Prefeitura de Ribeirópolis',
'897892344',
'SE',
'Ribeirópolis',
'Centro',
'2344444',
'Rua Teste',
'122',
'Qualquercoisaaqui');
```
> Implementado caso de uso Manter Área de Serviço

- Codigo/AgendeMeWeb/AgendeMeWeb.csproj
- Codigo/AgendeMeWeb/Controllers/CidadaoController.cs
- Codigo/AgendeMeWeb/Mappers/CidadaoProfile.cs
- Codigo/AgendeMeWeb/Models/CidadaoViewModel.cs
- Codigo/AgendeMeWeb/Program.cs
- Codigo/AgendeMeWeb/Views/Cidadao/Create.cshtml
- Codigo/AgendeMeWeb/Views/Cidadao/Delete.cshtml
- Codigo/AgendeMeWeb/Views/Cidadao/Details.cshtml
- Codigo/AgendeMeWeb/Views/Cidadao/Edit.cshtml
- Codigo/AgendeMeWeb/Views/Cidadao/Index.cshtml
- Codigo/Core/Service/ICidadaoService.cs
- Codigo/Service/CidadaoService.cs
Boa noite.
A implementação do caso de uso "Manter Cidadão" foi realizada. 
Por favor, realizar as devidas revisões referente a implementação.
Obs.: Abaixo está um script para auxiliar nos testes.
`insert into cidadao (nome, cpf, dataNascimento, sus, telefone, email, cep, estado, cidade, bairro, rua, numeroCasa, sexo, tipoCidadao, complemento, idOrgaoPublico, idPrefeitura)
values('José Vinícius de Carvalho Oliveira', '205.548-200-88','2001-02-02','205451-14','79 88852115', 'vini@gmail.com','49500-00','SE','Moita Bonita','Povoado Saquinho','Rua A','S/N','M','Profissional','Sem complemento',null,null)`
> Implementação do caso de uso Manter Cidadão

- Codigo/AgendeMeWeb/Controllers/AgendaDoServicoController.cs
- Codigo/AgendeMeWeb/Mappers/AgendaDoServicoProfile.cs
- Codigo/AgendeMeWeb/Models/AgendaDoServicoViewModel.cs
- Codigo/AgendeMeWeb/Program.cs
- Codigo/AgendeMeWeb/Views/AgendaDoServico/Create.cshtml
- Codigo/AgendeMeWeb/Views/AgendaDoServico/Delete.cshtml
- Codigo/AgendeMeWeb/Views/AgendaDoServico/Details.cshtml
- Codigo/AgendeMeWeb/Views/AgendaDoServico/Edit.cshtml
- Codigo/AgendeMeWeb/Views/AgendaDoServico/Index.cshtml
- Codigo/Core/Service/IAgendaDoServicoService.cs
- Codigo/Service/AgendaDoServicoService.cs
Tendo em mente a implementação do caso de uso "Manter Agenda do Servico", revisar o código dos seguintes arquivos:
- Core > Service > IAgendaDoServicoService.cs
- Service > AgendaDoServicoService.cs
- AgendeMeWeb > Models > AgendaDoServicoViewModel.cs
- AgendeMeWeb > Mappers > AgendaDoServicoProfile.cs
- AgendeMeWeb > Controllers > AgendaDoServicoController.cs
- AgendeMeWeb > Views > AgendaDoServico > Index.cshtml
- AgendeMeWeb > Views > AgendaDoServico > Create.cshtml
- AgendeMeWeb > Views > AgendaDoServico > Delete.cshtml
- AgendeMeWeb > Views > AgendaDoServico > Detail.cshtml
- AgendeMeWeb > Views > AgendaDoServico > Edit.cshtml
> Branch gabriel245 - Implementando o caso de uso Manter Agenda do Servico 

- Codigo/AgendeMeWeb/AgendeMeWeb.csproj
Com a versão 6.0.10 desse pacote é resolvido o bug de geração de código das views. Além disso, é necessário atualizar o visual studio.
> Adicionado pacote Code Generation Design

- Codigo/AgendeMeWeb/Models/AgendarServicoViewModel.cs
Verificar se todos os atributos do arquivo "AgendarServicoViewModel.cs" estão com os seus atributos de validação.
> Os atributos de validação foram adicionados. Done #262

- Codigo/AgendeMeWeb/Models/AgendarServicoViewModel.cs
Verificar as mudanças feitas no código, tendo em vista o problema relatado na issue #276. Sendo assim, revise e determine se alterações foram realizadas conforme o solicitado.
> Mundanças no arquivo AgendarServicoViewModel.cs

- Codigo/AgendeMeWeb/Controllers/OrgaoPublicoController.cs
- Codigo/AgendeMeWeb/Mappers/OrgaoPublicoProfile.cs
- Codigo/AgendeMeWeb/Models/OrgaoPublicoViewModel.cs
- Codigo/AgendeMeWeb/Program.cs
- Codigo/AgendeMeWeb/Views/OrgaoPublico/Create.cshtml
- Codigo/AgendeMeWeb/Views/OrgaoPublico/Delete.cshtml
- Codigo/AgendeMeWeb/Views/OrgaoPublico/Details.cshtml
- Codigo/AgendeMeWeb/Views/OrgaoPublico/Edit.cshtml
- Codigo/AgendeMeWeb/Views/OrgaoPublico/Index.cshtml
- Codigo/Core/Service/IOrgaoPublicoService.cs
- Codigo/Service/OrgaoPublicoService.cs
Boa noite. 
A implementação do caso de uso Manter Órgão Público foi finalizada. 
Solicito a revisão das alterações realizadas.
> Implementação do caso de uso Manter Órgão Público 

- Codigo/AgendeMe.sln
- Codigo/ServiceTests/AgendaDoServicoServiceTests.cs
- Codigo/ServiceTests/AgendamentoServiceTests.cs
- Codigo/ServiceTests/AreaDeServicoServiceTests.cs
- Codigo/ServiceTests/CargoServiceTests.cs
- Codigo/ServiceTests/CidadaoServiceTests.cs
- Codigo/ServiceTests/OrgaoPublicoServiceTests.cs
- Codigo/ServiceTests/PrefeituraServiceTests.cs
- Codigo/ServiceTests/ServiceTests.csproj
- Codigo/ServiceTests/ServicoPublicoServiceTests.cs
Boa noite.
O projeto "ServiceTests" foi adicionado a solução. Além disso, foram adicionadas as classes de teste das classes de serviço no projeto em questão.
Além disso, foi adicionado a biblioteca referente ao banco de dados em memória, de modo que, a versão instalada foi a 5.0.10. Assim como, está presente no projeto "biblioteca-es".
Por favor, realizar a revisão cuidadosa das alterações realizadas.
> Criação do projeto "ServiceTests" e das classes de testes do Service

- Codigo/AgendeMeWeb/Controllers/PrefeituraController.cs
- Codigo/AgendeMeWebTests/Controllers/PrefeituraControllerTests.cs
Revisar:
- Classe PrefeituraControllerTests :
1º passo: Analisar se os métodos da classe estão implementados corretamentes;
2º passo: Executar a classe e verificar se todos os testes da mesma foram aprovados;
> Implementado testes para a classe PrefeituraController

- Codigo/AgendeMeWeb/Controllers/OrgaoPublicoController.cs
- Codigo/AgendeMeWebTests/Controllers/OrgaoPublicoControllerTests.cs
Revisar:
- Classe OrgaoPublicoControllerTests:
1º passo: Verificar toda a estrutura do código.
2º passo: Executar os teste e verificar se foram aprovados.
- Classe OrgaoPublicoController:
1º passo: Verificar o método Delete() , tendo como objetivo determinar se a alteração feita no mesmo causará algum impacto negativo no funcionamento do projeto.
> Classe OrgaoPublicoControllerTests

- Codigo/Service/AreaDeServicoService.cs
- Codigo/ServiceTests/AreaDeServicoServiceTests.cs
Boa noite.
Implementação dos métodos de teste referentes a classe AreaDeServicoServiceTests foi realizada. De modo que, o método "Delete" da classe AreaDeServicoService precisou ser modificado, uma vez que, a implementação anterior gerava problemas para o teste de tal método.
Por favor, realizar atenciosamente a revisão das modificações realizadas.
> Implementação dos métodos de teste referentes a classe AreaDeServicoServiceTests

- Codigo/AgendeMeWeb/Controllers/CidadaoController.cs
- Codigo/AgendeMeWeb/Views/Cidadao/Details.cshtml
- Codigo/Core/DTO/CidadaoDTO.cs
- Codigo/Core/Service/ICidadaoService.cs
- Codigo/Service/CidadaoService.cs
Boa noite.
A implementação da tela 01_01 do caso de uso "Manter Cidadão" foi realizada. Para uma melhor implementação, foi desenvolvido um DTO. 
Solicito a revisão das alterações realizadas.
> Implementação da tela 01_01 do caso de uso "Manter Cidadão"

- Codigo/AgendeMeWeb/Models/CargoViewModel.cs
- Codigo/AgendeMeWeb/Views/Cargo/Create.cshtml
> Criada tela 12_01 do caso de uso Manter Cargo. 

- Codigo/AgendeMeWeb/Views/Cargo/Create.cshtml
> Corrigindo margin e tamanho do botão de cadastro na tela XL

- Codigo/AgendeMeWeb/Views/Cargo/Edit.cshtml
> Tela 12_02 personalizada de acordo com protótipo.

- Codigo/AgendeMeWebTests/Controllers/AgendarServicoControllerTests.cs
> Implementado testes para a controller AgendarServico

- Codigo/ServiceTests/ServicoPublicoServiceTests.cs
Revisar a implementação da classe de teste ServicoPublicoServiceTests (caminho: AgendeMe\Codigo\ServiceTests)
> classe ServicoPublicoServiceTests 

- Codigo/AgendeMeWeb/Views/Cidadao/Edit.cshtml
Boa tarde.
A implementação da tela 03_01 foi finalizada.
De maneira que, futuramente a mesma deve ser evoluída. Uma vez que, também será tratada a questão do CEP.
Solicito a revisão das alterações realizadas. Desde já, agradeço.
> Implementação da tela 01_03

- Codigo/ServiceTests/CidadaoServiceTests.cs
Boa noite!
O classe de teste do caso de uso Manter Cidadão foi finalizada. 
Solicito a revisão das modificações realizadas. Desde já, agradeço.
> Implementação da classe de teste do caso de uso Manter Cidadão

- AnaliseProjeto/Dump-AgendeMe.sql
Verificar se dump do banco de dados está localizado no local correto. Além disso, para acessar o arquivo basta seguir o seguinte caminho: AgendeMe\AnaliseProjeto.
> Dump do banco de dados

- .github/workflows/sonarqube.yml
Adicionando o arquivo .yml. Done #360
> Configurando o SonarQube

- Codigo/AgendeMeWebTests/Controllers/CargoControllerTests.cs
- Verificar se todos os testes da classe CargoControllerTest estão funcionando corretamente após as alterações realizadas.
- Verificar se os dados introduzidos são mais realistas que os anteriores
> Dados Modificados

- Codigo/ServiceTests/OrgaoPublicoServiceTests.cs
Revisar (caminho: AgendeMe\Codigo\ServiceTests\ [OrgaoPublicoServiceTests.cs](https://github.com/marcosdosea/AgendeMe/blob/Branch_Gabriel372/Codigo/ServiceTests/OrgaoPublicoServiceTests.cs)):
1º passo: revisar código implementado pela classe OrgaoPublicoServiceTests.
2º passo: executar os testes da classe OrgaoPublicoServiceTests.
> Testes da OrgaoPublicoSevice

- Codigo/ServiceTests/AgendamentoServiceTests.cs
Por favor, testem e vejam se também passa nos testes.
> Add teste para AgendamentoService

- Codigo/AgendeMeWebTests/Controllers/DiaAgendamentoControllerTests.cs
Por favor, testem e vejam se também passa nos testes.
> Add teste para DiaAgendamentoController

- Codigo/ServiceTests/PrefeituraServiceTests.cs
Boa noite!
Os métodos de teste referentes a classe PrefeituraServiceTests foram atualizados com dados mais próximos possíveis aos dados reais de utilização do usuário. 
Solicito a revisão das alterações realizadas e a execução dos casos de teste referentes. Desde já, agradeço.
> Atualização nos métodos de teste referentes a classe PrefeituraServiceTests

- Codigo/AgendeMeWebTests/Controllers/AreaDeServicoControllerTests.cs
Boa noite!
A classe AreaDeServicoControllerTests foi modificada para atender mais fielmente os testes referentes. De modo que, determinados dados foram atualizados visando a realização de testes com dados mais reais possíveis.
Solicito a revisão das alterações realizadas. Desde já, agradeço!
> Atualização e refatoração da classe AreaDeServicoControllerTests

- Testes/Testes_ManterPrefeitura.side
Arquivo contém a automatização dos casos de teste citados na descrição da issue #392.
> Manter Prefeitura - Testes Automatizados

- Codigo/AgendeMeWeb/Models/CargoViewModel.cs
- Codigo/AgendeMeWeb/Views/Cargo/Index.cshtml
Aplicação do design a tela de Index/List do caso de uso Manter Cargo.
> Tela 12_03(index/list) do caso de uso Manter Cargo

- Codigo/AgendeMeWeb/Views/AgendaDoServico/Index.cshtml
- Codigo/AgendeMeWeb/wwwroot/css/agendaDoServico.css
> Design na tela LIST de Agenda de Serviço (Tela 07_01)

- AnaliseProjeto/Dump-AgendeMe.sql
- Execute o dump e verifique se é possível autenticar com o usuário CPF: 111111111111111 Senha: 123456
- Atualização de clínicas com nomes de clínicas de Itabaiana
- Cadastrado prefeitura de Itabaiana
> Atualizar dump de dados com infos próximas da realidade

- Codigo/AgendeMeWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
- Codigo/AgendeMeWeb/Controllers/AgendarServicoController.cs
- Codigo/AgendeMeWeb/Helpers/ApplicationUserClaims.cs
- Codigo/AgendeMeWeb/Program.cs
- Codigo/AgendeMeWeb/Views/AgendarServico/AgendarServicoDias.cshtml
- Codigo/AgendeMeWeb/Views/AgendarServico/AgendarServicoHoras.cshtml
- Codigo/AgendeMeWeb/Views/AgendarServico/AreasDeServico.cshtml
- Codigo/AgendeMeWeb/Views/AgendarServico/ConfirmarAgendamento.cshtml
- Codigo/AgendeMeWeb/Views/AgendarServico/Index.cshtml
- Codigo/AgendeMeWeb/Views/AgendarServico/OrgaosPublicos.cshtml
- Codigo/AgendeMeWeb/Views/AgendarServico/ServicosPublicos.cshtml
- Codigo/AgendeMeWeb/Views/Shared/_Layout.cshtml
- Codigo/AgendeMeWeb/Views/Shared/_LoginPartial.cshtml
- Codigo/AgendeMeWeb/wwwroot/css/agendarServico.css
- Codigo/AgendeMeWeb/wwwroot/js/agendar-servico.js
- Codigo/AgendeMeWeb/wwwroot/js/cookie.js
- Codigo/Core/DTO/ConfirmarAgendamentoDTO.cs
- Codigo/Core/Service/ICidadaoService.cs
- Codigo/Service/CidadaoService.cs
- Codigo/Service/DiaAgendamentoService.cs
- Acesse com o cidadão CPF: 111111111111111 Senha: 123456
- Realize um agendamento
- Volte pelas telas de agendamento
- Opcional: Vá até o final do agendamento sem estar autenticado, na tela de confirmar, crie um acesso ou acesse com o anterior e tente confirmar o agendamento.
Obs: Essa mensagem deve aparecer caso o cidadão não esteja autenticado
- Botão voltar em todas as telas de agendamento
> Funcionalidades de Agendamento

- Codigo/AgendeMe.sln
- Codigo/AgendeMeWeb/AgendeMeWeb.csproj
- Codigo/AgendeMeWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml
- Codigo/AgendeMeWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
- Codigo/AgendeMeWeb/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml
- Codigo/AgendeMeWeb/Areas/Identity/Pages/Account/ResetPassword.cshtml
- Codigo/AgendeMeWeb/Areas/Identity/Pages/Account/ResetPasswordConfirmation.cshtml
- Codigo/AgendeMeWeb/Program.cs
- Codigo/Email/Email.csproj
- Codigo/Email/Interface/IEmailService.cs
- Codigo/Email/Models/EmailModel.cs
- Codigo/Email/Models/SMTPModel.cs
- Codigo/Email/Properties/launchSettings.json
- Codigo/Email/Service/EmailService.cs
- Criação do projeto de email
- Ajuste de classes geradas automaticamente pelo identity para usar o projeto de email para redefinir a senha
> Implementação de redefiniçao de Senha

- Codigo/AgendeMeWeb/Areas/Identity/Pages/Account/Login.cshtml
> Funcionalidade de ver senha no login
